### ISSUE TITLE
"TCPDF_PARSER ERROR: Unable to find startxref"

### ISSUE THREAD

**Issue by Javilop** [tecnickcom/TCPDF#193]
**The problem**

I'm using https://pdfparser.org/ that is based in TCPDF. It works fine with several PDFs but when I try some PDFs it gives me this error. For example with this PDF: https://www.dropbox.com/s/953syp2n16m6gir/p6.pdf?dl=0

**Error:**

Fatal error: Uncaught Exception: TCPDF_PARSER ERROR: Unable to find startxref in /Applications/MAMP/htdocs/msci/pdfparser-master/vendor/tecnickcom/tcpdf/tcpdf_parser.php:807 Stack trace: #0 /Applications/MAMP/htdocs/msci/pdfparser-master/vendor/tecnickcom/tcpdf/tcpdf_parser.php(173): TCPDF_PARSER->Error('Unable to find ...') #1 /Applications/MAMP/htdocs/msci/pdfparser-master/vendor/tecnickcom/tcpdf/tcpdf_parser.php(117): TCPDF_PARSER->getXrefData() #2 /Applications/MAMP/htdocs/msci/pdfparser-master/src/Smalot/PdfParser/Parser.php(93): TCPDF_PARSER->__construct('%PDF-1.4\n%\xAA\xAB\xAC\xAD\n...') #3 /Applications/MAMP/htdocs/msci/pdfparser-master/src/Smalot/PdfParser/Parser.php(81): Smalot\PdfParser\Parser->parseContent('%PDF-1.4\n%\xAA\xAB\xAC\xAD\n...') #4 /Applications/MAMP/htdocs/msci/pdfparser-master/prueba.php(8): Smalot\PdfParser\Parser->parseFile('p6.pdf') #5 {main} thrown in /Applications/MAMP/htdocs/msci/pdfparser-master/vendor/tecnickcom/tcpdf/tcpdf_parser.php on line 807

**Comment by trolikua** [comment]
Hi @Javilop,

I caught the same error. Could you explain how did you fix it?

Thx.

**Comment by nicolaasuni** [comment]
Thank you for reporting this. TCPDF 6 is now a legacy project and is officially **deprecated**, so no further fixes or features will be merged into this repository. As part of this transition, we are closing older issues. Please migrate to **[tc-lib-pdf](https://github.com/tecnickcom/tc-lib-pdf)** and, if the same problem still occurs there, open a new issue with updated reproduction steps. For more context, see the pinned announcement: [Thank You - and the Future of TCPDF](https://github.com/tecnickcom/TCPDF/issues/867).
