### ISSUE TITLE
Uncaught Error: Unsupported operand types in vendor/tecnickcom/tcpdf/tcpdf.php:8849

### ISSUE THREAD

**Issue by williamdes** [tecnickcom/TCPDF#322]
```
Fatal error</b>:  Uncaught Error: Unsupported operand types in vendor/tecnickcom/tcpdf/tcpdf.php:8849
Stack trace:
#0 vendor/tecnickcom/tcpdf/tcpdf.php(9472): TCPDF-&gt;_putfonts()
#1 vendor/tecnickcom/tcpdf/tcpdf.php(9989): TCPDF-&gt;_putresources()
#2 vendor/tecnickcom/tcpdf/tcpdf.php(3005): TCPDF-&gt;_enddoc()
#3 vendor/tecnickcom/tcpdf/tcpdf.php(10420): TCPDF-&gt;Close()
#4 libraries/classes/Plugins/Export/ExportPdf.php(157): TCPDF-&gt;getPDFData()
#5 libraries/classes/Controllers/ExportController.php(632): PhpMyAdmin\Plugins\Export\ExportPdf-&gt;exportFooter()
#6 libraries/classes/Routing.php(92): PhpMyAdmin\Controllers\ExportController-&gt;index(Array)
#7 index. in <b>vendor/tecnickcom/tcpdf/tcpdf.php</b> on line <b>8849</b><br />
```

```php
					foreach ($info['fontkeys'] as $fontkey) {
						$fontinfo = $this->getFontBuffer($fontkey);
						$subsetchars += $fontinfo['subsetchars'];
					}
```

**Comment by williamdes** [comment]
Probably fixed
