### ISSUE TITLE
TOC bug in php 8?

### ISSUE THREAD

**Issue by cstdenis** [tecnickcom/TCPDF#472]
Argument #2 ($times) must be greater than or equal to 0 in vendor/tecnickcom/tcpdf/tcpdf.php:21765
Stack trace:
#0 vendor/tecnickcom/tcpdf/tcpdf.php(21765): str_repeat(' ', -3)
#1 extensions/tcpdf/ETcPdf.php(94): TCPDF->addHTMLTOC(1, 'INDEX', Array, true, 'B', Array)

Version     : 6.4.4
PHP 8.0.12 

Code that invokes the error
`			$bookmark_templates[0] = '<table border="0" cellpadding="3" cellspacing="0">
							<tr>
								<td width="25mm"></td>
								<td width="105mm"><span style="font-weight:bold;font-size:12pt;color:black;">#TOC_DESCRIPTION#</span></td>
								<td width="25mm"><span style="font-family:courier;font-weight:bold;font-size:12pt;color:black;" align="right">#TOC_PAGE_NUMBER#</span></td>
								<td width="25mm"></td>
							</tr>
							</table>';

			$pdf->addHTMLTOC(1, 'INDEX', $bookmark_templates, true, 'B', array(128,0,0));`

**Comment by cstdenis** [comment]
This is triggered when the document has > 999 pages. addTOC() works, but addHTMLTOC() is broken.

**Comment by nicolaasuni** [comment]
Thank you for reporting this. TCPDF 6 is now a legacy project and is officially **deprecated**, so no further fixes or features will be merged into this repository. As part of this transition, we are closing older issues. Please migrate to **[tc-lib-pdf](https://github.com/tecnickcom/tc-lib-pdf)** and, if the same problem still occurs there, open a new issue with updated reproduction steps. For more context, see the pinned announcement: [Thank You - and the Future of TCPDF](https://github.com/tecnickcom/TCPDF/issues/867).
