### ISSUE TITLE
Undefined array key 26085  in tcpdf.php line 22263 

### ISSUE THREAD

**Issue by liayn** [tecnickcom/TCPDF#580]
version 6.6.1

affected line:
`if ((!$intag) AND (!$skip) AND TCPDF_FONT_DATA::$uni_type[$char] == 'L') {`

**Comment by williamdes** [comment]
Can you provide some code on how you trigger this?
Or the full stack trace?

**Comment by liayn** [comment]
I'm sorry, no. We just found it in the logs.
I can try to reproduce, but I suspect a case, where a really large dataset is used to create PDF.
But the fix is trivial:
`if ((!$intag) AND (!$skip) AND (TCPDF_FONT_DATA::$uni_type[$char] ?? '') == 'L') {`

**Comment by williamdes** [comment]
Okay

Yeah and using isset because `??` is php 7+ only haha

**Comment by liayn** [comment]
I'm totally fine with a tcpdf v7 that is php8.1+ only.
php v7 is dead already... so that's it

**Comment by williamdes** [comment]
Yeah but welcome to the long long term support
We support php 5.x+ until 8.2 here

**Comment by williamdes** [comment]
Thanks for reporting this issue, we will try to reproduce it because tests are important and fix it

**Comment by annuh** [comment]
We are facing the same issue, for example when adding this string to a PDF `斯 لارس`:

```
Warning: Undefined array key 25289

#0 /var/task/vendor/tecnickcom/tcpdf/tcpdf.php(4113): TCPDF_FONTS::utf8Bidi(Array, '\\xE6\\x8B\\x89\\xE7\\x88\\xBE\\xE6...', false, true, Array)",
#1 /var/task/vendor/tecnickcom/tcpdf/tcpdf.php(18523): TCPDF->GetStringWidth('\\xE6\\x8B\\x89\\xE7\\x88\\xBE\\xE6...')",
#2 /var/task/vendor/tecnickcom/tcpdf/tcpdf.php(5934): TCPDF->writeHTML('    <p style=\"f...', true, false, true, true, '')",
#3 /var/task/vendor/tecnickcom/tcpdf/tcpdf.php(17261): TCPDF->MultiCell(64.249217935349, 0, '    <p style=\"f...', 1, '', false, 0, 0, 0.0, true, 0, true, true, 0, 'T', false)",
```

It seems some Unicode characters are missing from this list https://github.com/tcpdf-clone/tcpdf/blob/master/include/tcpdf_font_data.php#L10617.

We are using v6.6.5.

**Comment by nicolaasuni** [comment]
Thank you for reporting this. TCPDF 6 is now a legacy project and is officially **deprecated**, so no further fixes or features will be merged into this repository. As part of this transition, we are closing older issues. Please migrate to **[tc-lib-pdf](https://github.com/tecnickcom/tc-lib-pdf)** and, if the same problem still occurs there, open a new issue with updated reproduction steps. For more context, see the pinned announcement: [Thank You - and the Future of TCPDF](https://github.com/tecnickcom/TCPDF/issues/867).
