### ISSUE TITLE
decodeFilterFlateDecode error

### ISSUE THREAD

**Issue by swbittib** [tecnickcom/TCPDF#766]
se si prova a parsare il file in allegato si riceve il seguente errore:

[28-Nov-2024 15:55:05 Europe/Rome] PHP Fatal error:  Uncaught Exception: TCPDF_PARSER ERROR: [pdf-test.pdf](https://github.com/user-attachments/files/17949647/pdf-test.pdf): invalid code in /................/tcpdf/include/tcpdf_filters.php:474
Stack trace:
#0 /..................../tcpdf/include/tcpdf_filters.php(359): TCPDF_FILTERS::Error('decodeFilterFla...')
#1 /..................../tcpdf/include/tcpdf_filters.php(94): TCPDF_FILTERS::decodeFilterFlateDecode('\e\x9F2yH\t\xD4\x1F\x8D\x87't<\xB3\xA8...')
#2 /..................../tcpdf/tcpdi_parser.php(1314): TCPDF_FILTERS::decodeFilter('FlateDecode', '\e\x9F2yH\t\xD4\x1F\x8D\x87't<\xB3\xA8...')
#3 /..................../tcpdf/tcpdi_parser.php(1253): tcpdi_parser->_rebuildContentStream(Array)
#4 /..................../tcpdf/tcpdi.php(192): tcpdi_parser->getContent()
#5 /..................../PDFMerger.php(105): TCPDI->importPage(1)
#6 printpdf3.php(518): PDFMerger\PDFMerger->merge('file', '/xxxxxxxxx/xxxxxxxxxxxx...')
#7 {main}
  thrown in /..................../tcpdf/include/tcpdf_filters.php on line 474
  
  
[pdf-test.pdf](https://github.com/user-attachments/files/17949666/pdf-test.pdf)

**Comment by nicolaasuni** [comment]
Thank you for reporting this. TCPDF 6 is now a legacy project and is officially **deprecated**, so no further fixes or features will be merged into this repository. As part of this transition, we are closing older issues. Please migrate to **[tc-lib-pdf](https://github.com/tecnickcom/tc-lib-pdf)** and, if the same problem still occurs there, open a new issue with updated reproduction steps. For more context, see the pinned announcement: [Thank You - and the Future of TCPDF](https://github.com/tecnickcom/TCPDF/issues/867).
