### ISSUE TITLE
Trying to access array offset on null

### ISSUE THREAD

**Issue by andruha** [tecnickcom/TCPDF#769]
I get an error in php 8.4.1
In PHP 8.3 everything is fine

`yii\base\ErrorException: Trying to access array offset on null
#17 /var/composer/vendor/tecnickcom/tcpdf/include/barcodes/qrcode.php(761): yii\base\ErrorHandler::handleError
#16 /var/composer/vendor/tecnickcom/tcpdf/include/barcodes/qrcode.php(761): QRcode::setFrameAt
#15 /var/composer/vendor/tecnickcom/tcpdf/include/barcodes/qrcode.php(724): QRcode::encodeMask
#14 /var/composer/vendor/tecnickcom/tcpdf/include/barcodes/qrcode.php(687): QRcode::encodeString
#13 /var/composer/vendor/tecnickcom/tcpdf/include/barcodes/qrcode.php(630): QRcode::__construct
#12 /var/composer/vendor/tecnickcom/tcpdf/tcpdf_barcodes_2d.php(299): TCPDF2DBarcode::setBarcode
#11 /var/composer/vendor/tecnickcom/tcpdf/tcpdf_barcodes_2d.php(69): TCPDF2DBarcode::__construct
#10 /var/composer/vendor/tecnickcom/tcpdf/tcpdf.php(15666): TCPDF::write2DBarcode`

**Comment by andruha** [comment]
Error when `opcache.jit=1235`
No error when `opcache.jit=1255`

**Comment by williamdes** [comment]
Quite a weird one
For now the policy of @nicolaasuni is to not change qrcodes to much and update the new library

**Comment by nicolaasuni** [comment]
Thank you for reporting this. TCPDF 6 is now a legacy project and is officially **deprecated**, so no further fixes or features will be merged into this repository. As part of this transition, we are closing older issues. Please migrate to **[tc-lib-pdf](https://github.com/tecnickcom/tc-lib-pdf)** and, if the same problem still occurs there, open a new issue with updated reproduction steps. For more context, see the pinned announcement: [Thank You - and the Future of TCPDF](https://github.com/tecnickcom/TCPDF/issues/867).
